spring.application.name=volante

# Configurações do servidor
server.port=8080

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://aulasprog.us.to:5432/volante_express
spring.datasource.username=postgres
spring.datasource.password=senaipatobranco

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurações de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
spring.jackson.time-zone=America/Sao_Paulo

#Configurações de Arquivos MultipartFile
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

